//@koala-prepend "content/orders/privateOrders/conf.js"
//@koala-prepend "content/orders/privateOrders/eventsHandlers.js",
//@koala-prepend "content/orders/privateOrders/listOfPrivateOrders.js",
//@koala-prepend "content/orders/theOrderDetail/listOfCards.js",
//@koala-prepend "content/orders/theOrderDetail/theOrderDetail.js",
//@koala-prepend "content/orders/managePrivateOrders.js",
//@koala-prepend "content/orders/manageAddingQuickOrder.js",    
//@koala-prepend "content/customers/listOfCustomers.js",    
//@koala-prepend "layout/mainToolbar.js",
//@koala-prepend "layout/leftSidebar.js",                
//@koala-prepend "layout/content.js"