#!/bin/bash

# katalog z logami
LOGS="/home/dexter/logs/email/"

# folder skryptu php
PHP_SCRIPT_FOLDER="/var/www/skp/skp.lan/public_html/app/Skrypty/"

# czas logowania z dokładnością do godzin
logtime=`date +"%Y-%m-%d_%H"`
suffix="-email.log"

#pełna nazwa pliku do logowania
logfile="$LOGS$logtime$suffix"

cd $PHP_SCRIPT_FOLDER
#php skrypt do maili
php poczta.php >> $logfile

