#!/bin/bash
#ble ble coś tam test dskjfksdjfk
LOGS="/home/dexter/logs/email/"                    							# katalog z logami
SC_FOLDER="/var/www/skp/skp.lan/public_html/app/Skrypty/"	# folder skryptu php
logtime=`date +"%Y-%m-%d_%H"`           							# czas logowania z dokładnością do godzin
suffix="-email.log"

logfile="$LOGS$logtime$suffix"										#pełna nazwa pliku do logowania

cd $SC_FOLDER
php poczta.php >> $logfile 											#php skrypt do maili

