FROM nginx:alpine

WORKDIR /var/www/html

# Nginx
RUN rm /etc/nginx/conf.d/default.conf
ADD docker/skp.conf /etc/nginx/conf.d

# Cake PhP
COPY ["Inne rzeczy/cakephp.tar.gz", "."]
RUN tar -xf cakephp.tar.gz && rm cakephp.tar.gz
COPY [".", "."]
# RUN chown www-data:www-data -R /cake_install